version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    env_file:
      - ./services/postgres/env/postgres.env
    ports:
      - '5432:5432'
    volumes:
#      - ./services/postgres/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - postgres-data:/var/lib/postgresql/data
# ホスト上でデータを管理する場合
#      - ./services/postgres/data:/var/lib/postgresql/data
      - ./services/postgres/init:/docker-entrypoint-initdb.d
  web-app:
    build:
      context: ./dockerfiles/web-app
      args:
        TZ: 'Asia/Tokyo'
        COMPOSER_VERSION: 1
    image: ot-mikami/template-laravel-01
    restart: always
    env_file:
      - ./services/web-app/env/web-app.env
    volumes:
      - ./services/web-app/conf/php.ini:/etc/php7/php.ini
      - ./services/web-app/conf/httpd.conf:/etc/apache2/httpd.conf
      - ./htdocs:/var/www/localhost/htdocs
      - ./services/web-app/log/apache2:/var/log/apache2
      - ./src:/usr/src
    ports:
      - '8001:80'
      - '8000:8000'
    links:
      - postgres

volumes:
  postgres-data:
    driver: local
